// Do not edit. This file is machine generated by the Resource DLL Wizard.

library LAb05;

{ITE} {DFMFileType} {ABOUT.dfm}
{ITE} {DFMFileType} {Main.dfm}
{ITE} {RCFileType} {Win32\Debug\LAb05_DRC.rc}

{$R 'ABOUT.dfm' 'AboutBox:TForm'}
{$R 'Main.dfm' 'Form_main:TForm'}
{$R 'Win32\Debug\LAb05_DRC.res' 'Win32\Debug\LAb05_DRC.rc'}

{$E RUS}

begin
end.
